run:
  name: lightgbm Test
  version: 1
  random_state: 42
  is_train: false
model:
  name: lightgbm
  hyperparameters:
    regularisation:
      max_depth: 4
      min_child_samples: 20
      reg_lambda: 1.0
      reg_alpha: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
      learning_rate: 0.1
      num_leaves: 15
    n_estimators: 1000
    early_stopping_rounds: 10
    scale_pos_weight: 1
    metric: binary_logloss
woe:
  enabled: true
  iv_threshold: 0.02
  metric: woe
  persistence: false
smote:
  enabled: true
  sampling_strategy: auto
  random_state: 42
correlation:
  enabled: true
  threshold: 0.8
evaluation:
  threshold_result:
    threshold: 0.027779146361888534
  constraints_result:
    recall:
      value: 0.8019863438857853
    f1:
      value: 0.18442088091353998
mlflow:
  tracking_uri: http://localhost:5000
  experiment_name: PD_modelling
  run_artifact_path:
    run_id: db104eaad66a438ca0e9026e1d0660f8
    binning_process:
      name: binning_process
      path: binning_process
      artifact_type: PKL
      ismodel: false
    model_fit:
      name: model_fit
      path: model_fit
      artifact_type: PKL
      ismodel: false


  preprocessing:
    scaler:
      enabled: true
      tracking_uri: http://localhost:5000
      experiment_name: PD_modelling
      run_id: a3b3a7f138634be08c84fc6df150d28a # todo ajouter automatiquement
      run_name: PD_scaler_preprocessing_v1
      run_role: preprocessing
      model_family: PD
      name: scaler
      path: scaler
      metadata_name: scaler_metadata
      artifact_type: PKL
      ismodel: false
      log_in_model_run: false


artifacts:
  log_model: true
  log_woe: true
  log_reports: true
