run:
  name: LightGBM LGD Multiclass Test
  version: 1
  random_state: 42
  is_train: false
model:
  name: LightGBM
  n_bins: 8
  hyperparameters: null
  grid_search: null
evaluation:
  regression_result:
    rmse:
      value: 0.2763284610663373
    dxy:
      value: 0.2609495631478002
  calibration_result:
    ece:
      value: 0.02476669007736647
mlflow:
  tracking_uri: http://localhost:5000
  experiment_name: LGD_modelling
  run_artifact_path:
    run_id: 5d1f5484377d453a97625d3c424ffdde
    lgd_discretizer:
      name: lgd_discretizer
      path: lgd_discretizer
      artifact_type: PKL
      ismodel: false
    lgd_bin_summary:
      name: lgd_bin_summary
      path: lgd_bin_summary
      artifact_type: CSV
      ismodel: false
    model_fit:
      name: model_fit
      path: model_fit
      artifact_type: PKL
      ismodel: false
  preprocessing:
    scaler:
      enabled: true
      tracking_uri: http://localhost:5000
      experiment_name: LGD_modelling
      run_id: 2037a443f35748359cc6d6d744490efa
      run_name: LGD_scaler_preprocessing_v1
      run_role: preprocessing
      model_family: LGD
      name: scaler
      path: scaler
      artifact_type: PKL
      ismodel: false
      log_in_model_run: false
