run_id: c941d55209d1427ca872ad2c7e146f73

#tracking_uri: "http://mlflow:5000"
tracking_uri: "http://mlflow:5000"
experiment_name: LGD_modelling

preprocessing:
  scaler:
    enabled: true
    tracking_uri: "http://mlflow:5000" #http://localhost:5000
    experiment_name: LGD_modelling
    run_id: 239eb675b01c481eacf5837cc911a393
    run_name: LGD_scaler_preprocessing_v1
    run_role: preprocessing
    model_family: LGD
    name: scaler
    path: scaler
    metadata_name: scaler_metadata
    artifact_type: PKL
    ismodel: false
    log_in_model_run: false

lgd_discretizer:
  name: lgd_discretizer
  path: lgd_discretizer
  artifact_type: PKL
  ismodel: false

lgd_bin_summary:
  name: lgd_bin_summary
  path: lgd_bin_summary
  artifact_type: CSV
  ismodel: false

model_fit:
  artifact_type: "PKL"
  ismodel: false
  name: "model_fit"
  path: "model_fit"




