run_id: b7142e5699114ccb8ea9808dc0f0fe69

#tracking_uri: "http://mlflow:5000"
tracking_uri: "http://localhost:5000"
experiment_name: "PD_modelling"

preprocessing:
  scaler:
    enabled: true
    tracking_uri: "http://localhost:5000"
    experiment_name: "PD_modelling"
    run_id: 7684096e6e254843846de27ab9df3607
    run_name: PD_scaler_preprocessing_v1
    run_role: preprocessing
    model_family: PD
    name: scaler
    path: scaler
    metadata_name: scaler_metadata
    artifact_type: PKL
    ismodel: false
    log_in_model_run: false

binning_process:
  artifact_type: "PKL"
  ismodel: false
  name: "binning_process"
  path: "binning_process"

model_fit:
  artifact_type: "PKL"
  ismodel: false
  name: "model_fit"
  path: "model_fit"

stacking_weights:
  artifact_type: "JSON"
  ismodel: false
  name: "stacking_weights"
  path: "stacking_weights"

scaler:
  artifact_type: "PKL"
  ismodel: false
  name: "scaler"
  path: "scaler"
